-- CAU 1:
CREATE TABLE HANGHANGKHONG(
    MAHANG VARCHAR(3),
    TENHANG VARCHAR(50),
    NGTL DATE,
    DUONGBAY NUMBER(4)
)

CREATE TABLE CHUYENBAY(
    MACB VARCHAR(5),
    MAHANG VARCHAR(3),
    XUATPHAT VARCHAR(50),
    DIEMDEN VARCHAR(50),
    BATDAU TIMESTAMP,
    TGBAY NUMBER(5,2)
)

CREATE TABLE NHANVIEN(
    MANV VARCHAR(5),
    HOTEN VARCHAR(50),
    GIOITINH VARCHAR(10),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR(50)
)

CREATE TABLE PHANCONG(
    MACB VARCHAR(5),
    MANV VARCHAR(5),
    NHIEMVU VARCHAR(50)
)

ALTER TABLE HANGHANGKHONG
   ADD CONSTRAINT MHK_PK PRIMARY KEY(MAHANG);

ALTER TABLE CHUYENBAY
   ADD CONSTRAINT CHUYENBAY_PK PRIMARY KEY(MACB);

ALTER TABLE CHUYENBAY
   ADD CONSTRAINT CHUYENBAY_FK FOREIGN KEY(MAHANG)
   REFERENCES HANGHANGKHONG(MAHANG);

ALTER TABLE NHANVIEN
   ADD CONSTRAINT NHANVIEN_PK PRIMARY KEY(MANV);

ALTER TABLE PHANCONG
   ADD CONSTRAINT PHANCONG_FK1 FOREIGN KEY(MACB)
   REFERENCES CHUYENBAY(MACB);

ALTER TABLE PHANCONG
   ADD CONSTRAINT PHANCONG_FK2 FOREIGN KEY(MANV)
   REFERENCES NHANVIEN(MANV);
   
ALTER TABLE PHANCONG
   ADD CONSTRAINT PHANCONG_PK PRIMARY KEY(MACB,MANV);
   
-- CAU 2:
--CHANGE DATE FORMAT
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/RRRR';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'DD/MM/RRRR/ HH24:MI:SSXFF';

INSERT INTO HANGHANGKHONG VALUES ('VN', 'Vietnam Airlines', '15/01/1956', 52);
INSERT INTO HANGHANGKHONG VALUES ('VJ', 'Vietjet Air', '25/12/2011', 33);
INSERT INTO HANGHANGKHONG VALUES ('BL', 'Jetstar Pacific Airlines', '01/12/1990', 13);

INSERT INTO CHUYENBAY VALUES ('VN550', 'VN', 'TP.HCM', 'Singapore', '20/12/2015 13:15:00' , 2);
INSERT INTO CHUYENBAY VALUES ('VJ331', 'VJ', 'Da Nang', 'Vinh', '28/12/2015 22:30:00', 1);
INSERT INTO CHUYENBAY VALUES ('BL696', 'BL', 'TP.HCM', 'Da Lat','24/12/2015 06:00:00', 0.5);

INSERT INTO NHANVIEN VALUES ('NV01', 'Lam Van Ben', 'Nam', '10/09/1978', '05/06/2000', 'Phi Cong');
INSERT INTO NHANVIEN VALUES ('NV02', 'Duong Thi Luc','Nu', '22/03/1989', '12/11/2013', 'Tiep Vien');
INSERT INTO NHANVIEN VALUES ('NV03', 'Hoang Thanh Tung', 'Nam', '29/07/1983', '11/04/2007', 'Tiep Vien');

INSERT INTO PHANCONG VALUES ('VN550', 'NV01', 'Co Truong');
INSERT INTO PHANCONG VALUES ('VN550', 'NV02', 'Tiep Vien');
INSERT INTO PHANCONG VALUES ('BL696','NV03', 'Tiep Vien Truong');

--CAU 3:
ALTER TABLE NHANVIEN
ADD CONSTRAINT CHUYENMON_CHECK CHECK(CHUYENMON = 'Phi Cong' or CHUYENMON = 'Tiep Vien');

--CAU 4:
CREATE OR REPLACE TRIGGER TG_BD_TL
BEFORE INSERT OR UPDATE OF BATDAU ON CHUYENBAY
FOR EACH ROW
DECLARE
   NGTL HANGHANGKHONG.NGTL%TYPE;
BEGIN
   SELECT NGTL
   INTO NGTL
   FROM HANGHANGKHONG HHK
   WHERE HHK.MAHANG = :NEW.MAHANG;
   
   IF :new.BATDAU < to_timestamp(NGTL, 'YYYY-MM-DD') THEN
      raise_application_error(-20111,'NGAY BAT DAU CHUYEN BAY PHAI LON HON NGAY THANH LAP');
   END IF;

END;

CREATE OR REPLACE TRIGGER TG_BD_TL_2
BEFORE INSERT OR UPDATE OF NGTL ON HANGHANGKHONG
FOR EACH ROW
DECLARE
   BATDAU CHUYENBAY.BATDAU%TYPE;
BEGIN
   FOR cur IN(SELECT BATDAU FROM CHUYENBAY CB
              WHERE CB.MAHANG = :NEW.MAHANG
              )
              LOOP
                 IF to_timestamp(:new.NGTL, 'YYYY-MM-DD') >= cur.BATDAU THEN
                    raise_application_error(-20111,'NGAY BAT DAU CHUYEN BAY PHAI LON HON NGAY THANH LAP');
                 END IF;
              END LOOP;
END;

--CAU 5:
SELECT*
FROM NHANVIEN
WHERE EXTRACT(MONTH FROM NGSINH) = 7 ;

--CAU 6:
SELECT CB.MACB, COUNT(MANV)
FROM CHUYENBAY CB JOIN PHANCONG PC ON CB.MACB = PC.MACB
GROUP BY CB.MACB
ORDER BY COUNT(*) DESC
fetch next 1 rows with ties;

--CAU 7:
SELECT HHK.MAHANG, CB.XUATPHAT, COUNT(MANV)
FROM HANGHANGKHONG HHK LEFT JOIN CHUYENBAY CB ON HHK.MAHANG = CB.MAHANG
LEFT JOIN PHANCONG PC ON CB.MACB = PC.MACB
GROUP BY HHK.MAHANG, CB.XUATPHAT
HAVING COUNT(PC.MANV) < 2 and CB.XUATPHAT = 'Da Nang'

--Cau 8:
SELECT* 
FROM NHANVIEN NV
WHERE NOT EXISTS(
        SELECT* FROM CHUYENBAY CB
        WHERE NOT EXISTS(
                  SELECT* FROM PHANCONG PC
                  WHERE PC.MACB = CB.MACB
                  AND PC.MANV = NV.MANV
                  )
                )
                