-- CAU 1:
CREATE TABLE USER1(
   UID1 VARCHAR(3) PRIMARY KEY,
   USERNAME VARCHAR(20),
   PASS VARCHAR(20),
   REGDAY DATE,
   NATIONALITY VARCHAR(20)
);

CREATE TABLE CHANNEL(
   CHANNELID VARCHAR(4) PRIMARY KEY,
   CNAME VARCHAR(20),
   SUBSCRIBES NUMBER(4),
   OWNNER VARCHAR(3),
   CREATED DATE
);

CREATE TABLE VIDEO(
   VIDEOID VARCHAR(10) PRIMARY KEY,
   TITLE VARCHAR(50),
   DURATION NUMBER(4),
   AGE NUMBER(2)
);

CREATE TABLE SHARE1(
   VIDEOID VARCHAR(10),
   CHANNELID VARCHAR(4)
);

ALTER TABLE CHANNEL 
   ADD CONSTRAINT FK_CHANNEL FOREIGN KEY(OWNNER)
   REFERENCES USER1(UID1);
   
ALTER TABLE SHARE1
   ADD CONSTRAINT PK_SHARE1 FOREIGN KEY(VIDEOID)
   REFERENCES VIDEO(VIDEOID)
   
ALTER TABLE SHARE1
   ADD CONSTRAINT PK_SHARE1_2 FOREIGN KEY(CHANNELID)
   REFERENCES CHANNEL(CHANNELID)
   
ALTER TABLE SHARE1
   ADD CONSTRAINT PK_SHARE PRIMARY KEY(VIDEOID, CHANNELID)
   
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/RRRR';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'DD/MM/RRRR/ HH24:MI:SSXFF';

-- CAU 2:
INSERT INTO USER1 VALUES('001', 'faptv', '123456abc', '01/01/2014', 'Viet Nam');
INSERT INTO USER1 VALUES('002', 'kemxoitv','@147869iii', '05/06/2015', 'Campuchia');
INSERT INTO USER1 VALUES('003', 'openshare', 'qwertyuiop', '12/05/2009', 'Viet Nam');

INSERT INTO CHANNEL VALUES('C120', 'FAP TV', 2343, '001', '02/01/2014');
INSERT INTO CHANNEL VALUES('C905', 'Kem Xoi TV', 1032, '002', '09/07/2015');
INSERT INTO CHANNEL VALUES('C357', 'OpenShare Cafe', 5064, '003', '10/12/2010');

INSERT INTO VIDEO VALUES('V100229', 'FAPtv Com Nguoi Tap 41 - Dot Nhap', 449, 18);
INSERT INTO VIDEO VALUES('V211002', 'Kem xoi: Tap 31 - May Kool tinh yeu cua anh', 312, 16);
INSERT INTO VIDEO VALUES('V400002', 'Noi tinh yeu ket thuc - Hoang Tuan', 378, 0);

INSERT INTO SHARE1 VALUES('V100229', 'C905');
INSERT INTO SHARE1 VALUES('V211002', 'C120');
INSERT INTO SHARE1 VALUES('V400002', 'C357');

--CAU 3:
ALTER TABLE USER1
MODIFY REGDAY DEFAULT SYSDATE;

--CAU 4:
CREATE OR REPLACE TRIGGER TG_BD_TL_1
BEFORE INSERT OR UPDATE OF CREATED ON CHANNEL
FOR EACH ROW
DECLARE
   REGDAY USER1.REGDAY%TYPE;
BEGIN
   SELECT REGDAY
   INTO REGDAY
   FROM USER1 U
   WHERE U.UID1 = :NEW.OWNNER;
   
   IF :new.CREATED < REGDAY THEN
      raise_application_error(-20111,'NGAY TAO KENH PHAI LON HON NGAY DANH KY');
   END IF;

END;

CREATE OR REPLACE TRIGGER TG_BD_TL_2
BEFORE INSERT OR UPDATE OF REGDAY ON USER1
FOR EACH ROW
DECLARE
   CREATED CHANNEL.CREATED%TYPE;
BEGIN
   FOR cur IN(SELECT CREATED FROM CHANNEL C
              WHERE C.OWNNER= :NEW.UID1
              )
              LOOP
                 IF :NEW.REGDAY > cur.CREATED THEN
                    raise_application_error(-20111,'NGAY TAO KENH PHAI LON HON NGAY DANH KY');
                 END IF;
              END LOOP;
END;

--CAU 5:
SELECT*
FROM VIDEO
WHERE AGE >= 16;

--CAU 6:
SELECT*
FROM CHANNEL
ORDER BY SUBSCRIBES DESC
fetch next 1 rows with ties;

--CAU 7:
SELECT V.VIDEOID, V.TITLE, COUNT(S.CHANNELID)
FROM VIDEO V LEFT JOIN SHARE1 S ON V.VIDEOID = S.VIDEOID
GROUP BY V.VIDEOID, V.TITLE
HAVING V.AGE = 18;
 

--CAU 8:
SELECT* 
FROM CHANNEL C
WHERE NOT EXISTS(
        SELECT* FROM VIDEO V
        WHERE NOT EXISTS(
                  SELECT* FROM SHARE1 S
                  WHERE C.CHANNELID = S.CHANNELID
                  AND V.VIDEOID = S.VIDEOID
                  )
                )
